# Trigger redeploy
# .github/workflows/cd-deploy.yml
name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name wiz-test --region us-east-1

    - name: Apply Deployment
      run: |
        kubectl apply -f k8s/tasky-deployment.yaml
        kubectl rollout status deployment tasky -n wiz
